name: Executar Playwright

on:
  issues:
    types: [opened]

jobs:
  playwright:
    # Só executa se a issue tiver a label 'run-playwright'
    if: contains(github.event.issue.labels.*.name, 'run-playwright')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Instalar dependências
        run: |
          pip install playwright psycopg2-binary pandas tqdm requests python-dotenv
          playwright install chromium
          playwright install-deps
      
      - name: Executar Playwright
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TABELA: ${{ secrets.TABELA }}
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scripts/client_cad_painel_neon.py
      
      - name: Comentar resultado
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅ Concluído' : '❌ Erro';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `${status}\n\nVerifique os logs para detalhes.`
            });
            
            // Fecha a issue
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
